name: execute phpunit

on:
  push:
    branches:
      - v2.0
  pull_request:
    branches:
      - v2.0

jobs:
  test:
    name: P${{ matrix.php_version }} - L${{ matrix.laravel }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ 7.3, 7.4, 8.0, 8.1 ]
        laravel: [ 8.*, 9.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.*
        exclude:
          - laravel: 9.*
            php_version: 7.3
          - laravel: 9.*
            php_version: 7.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: mbstring, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: PHPUnit check
        run: ./vendor/bin/phpunit
