name: execute phpunit

on:
  push:
    branches:
      - v2.0
  pull_request:
    branches:
      - v2.0

jobs:
  test:
    name: phpunit Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [ 7.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: PHPUnit check
        run: ./vendor/bin/phpunit
